// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsosjztfsejicxnuwfzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zb3NqenRmc2VqaWN4bnV3ZnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzE1MjEsImV4cCI6MjA1NzAwNzUyMX0.KSImuG8TBMsTAn3T9Plb0E0KsAMF-wvWNfec85zNFzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);